#!/bin/sh

if [ -f "$HOME/dotfiles/Brewfile" ]; then
	echo "Updating homebrew bundle..."
	brew bundle --file $HOME/dotfiles/Brewfile
fi

if [ -d "$HOME/.iterm2" ]; then
	echo "Setting iTerm preference folder"
	defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/dotfiles/iterm2.plist"
fi

echo "Setting defaults..."
source "$HOME/dotfiles/defaults.sh"


if command -v nvim >/dev/null 2>&1; then
  echo "Bootstraping Neovim"
  nvim '+PlugUpdate' '+PlugClean!' '+PlugUpdate' '+qall'
fi


echo "Updating the yadm repo origin URL"
yadm remote set-url origin "git@github.com:korsveien/dotfiles.git"

echo "Symlinking yadm repo to ~/.git in order to use tools like fork"
ln -s ~/.local/share/yadm/repo.git ~/.git

chsh -s fish
echo "Switched to fish, restart terminal to use!"

echo "...Done!"
exit 0

