vim.opt.clipboard = "unnamedplus"
vim.opt.hidden = true -- switch between buffers without saving changes
vim.opt.laststatus = 3 -- global statusline
vim.opt.number = true -- show line numbers
vim.opt.splitright = true
vim.opt.swapfile = false
vim.opt.swapfile = true
vim.opt.wrap = false
vim.opt_local.conceallevel = 2
