bind r source-file ~/.config/tmux/tmux.conf

set -g status-right '#(TZ=Asia/Tokyo date +月%m日%%d\ %%a\ %%H:%%M\) '
set -g base-index 1 # Start window numbering on 1
set -g mouse on
set -g mode-keys vi
set -g extended-keys on

bind | split-window -h
bind - split-window -v

bind -n M-t new-window
bind -n M-w if-shell '[ #{window_panes} -gt 1 ]' 'kill-pane' 'if-shell "[ #{session_windows} -gt 1 ]" "kill-window" ""'

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n 'M-{' previous-window
bind -n 'M-}' next-window

bind -n 'M-1' select-window -t 1
bind -n 'M-2' select-window -t 2
bind -n 'M-3' select-window -t 3
bind -n 'M-4' select-window -t 4
bind -n 'M-5' select-window -t 5
bind -n 'M-6' select-window -t 6
bind -n 'M-7' select-window -t 7
bind -n 'M-8' select-window -t 8
bind -n 'M-9' select-window -t 9

set -g automatic-rename on
set -g automatic-rename-format '#{pane_current_command} #{s|/Users/peder|~|:pane_current_path}'

set -g window-status-format ' #I: #{pane_current_command} #{s|/Users/peder|~|:pane_current_path} '
set -g window-status-current-format ' #I: #{pane_current_command} #{s|/Users/peder|~|:pane_current_path} '
set -g window-status-current-style bg=#181616,fg=green
